# Generated by Django 4.0.4 on 2022-05-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drfpost',
            old_name='author',
            new_name='prompt',
        ),
        migrations.RemoveField(
            model_name='drfpost',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drfpost',
            name='rating',
        ),
        migrations.AddField(
            model_name='drfpost',
            name='answer',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
